config/routes.rb
Rails.application.routes.draw do
  get '/friends/personal' => 'friends#personal'
  
  devise_for :users
  resources :friends
  # get 'home/index'
  get 'home/about'
  get 'home/contact'
  # root 'home#index'
  
  root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to:user

    def self.filter_user(user)
        
        where(user: user)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
    
  end

  def personal
    @friends = Friend.filter_user(current_user)
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # create new functions for user auth
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end


  def about
    @about_me = "My Name is Alan Contreras"
    @answer = 3 + 3
  end


  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%# <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name", :required => 'required' %>
  </div>

  <div class="field form-group">
    <%# form.label :last_name %> 
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name", :required => 'required' %>
  </div>

  <div class="field form-group">
    <%# <%= form.label :email %> 
    <%= form.email_field :email, class:"form-control", placeholder:"Email", :required => 'required' %>
  </div>

  <div class="field form-group">
    <%# <%= form.label :phone %>
    <%= form.telephone_field :phone, class:"form-control", placeholder:"Phone", :required => 'required', pattern:"[0-9]{10}" %>
  </div>

  <div class="field form-group">
    <%# <%= form.label :twitter %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter", :required => 'required' %>
  </div>

  <%# add new one for including user_id %>

 <%#  <%= current_user.id  we could also be calling .inspect %>
  <div class="field form-group">
    <%# <%= form.label :twitter %>
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden, :required => 'required' %>
  </div>
  <br/>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>
<br/>
<%= link_to 'Show', @friend, class:"btn btn-secondary" %>  
<%= link_to 'Delete', @friend, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= friend.user_id %></td>
        <td><%= link_to 'Show', friend %></td>
        <% if friend.user == current_user%>
          <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
          <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
          <td></td>
          <td></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>
<br/>
<%= render 'form', friend: @friend %>
<br/>
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/personal.html..erb
<% if user_signed_in?%>

  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <%# <th>User</th> %>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td>
            <%= link_to friend.first_name + " " + friend.last_name , friend %>
            
          </td>
          
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          
          
          <%# commented out portion with an if false %>
          <% if false%>
                    <td><%= friend.user_id %></td>
                    <td><%= link_to 'Show', friend %></td>
                    <% if friend.user == current_user%>
                      <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
                      <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <%else%>
                      <td></td>
                      <td></td>
                    <%end%>
          <% end %>


          <td><%= link_to 'Destroy', friend, class: "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>

<% else %>

  <h1>Hello World</h1>
  <p>Please Sign in</p>


<% end %>

app/views/friends/personal.html.erb
<% if user_signed_in?%>

  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <%# <th>User</th> %>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td>
            <%= link_to friend.first_name + " " + friend.last_name , friend %>
            
          </td>
          
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          
          
          <%# commented out portion with an if false %>
          <% if false%>
                    <td><%= friend.user_id %></td>
                    <td><%= link_to 'Show', friend %></td>
                    <% if friend.user == current_user%>
                      <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
                      <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <%else%>
                      <td></td>
                      <td></td>
                    <%end%>
          <% end %>


          <td><%= link_to 'Destroy', friend, class: "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>

<% else %>

  <h1>Hello World</h1>
  <p>Please Sign in</p>


<% end %>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %> |
    <%= @friend.phone %> |
    <%= @friend.twitter %> 
  </p>
  <br>

  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary"  %> 
  <%= link_to 'Delete', @friend, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Back', friends_path, class:"btn btn-dark"  %>
  
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Friends App", root_path, class:"navbar-brand" %>
    <%# <a class="navbar-brand" href="#">Friend App</a> %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     <%# <li class="nav-item active">
       <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
     </li> %>
      <li class="nav-item">
        <%= link_to "About Us", home_about_path, class:"nav-link" %>
        <%# <a class="nav-link" href="#">Link</a> %>
      </li>

      <%# commenting something out %>
      <% if false%>
                  <li class="nav-item">
                    <%= link_to "Friends", friends_path, class:"nav-link" %>
                  </li>
      <% end%>
      
      <li class="nav-item">
        <%= link_to "My Friends", friends_personal_path, class:"nav-link" %>
      </li>
    </ul>

    <ul class="navbar-nav ">
      <% if user_signed_in?%>
        <li class="nav-item">
            <%= link_to "Add Friends", new_friend_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Profile", edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <%else %>
            <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
            </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/home/about.html.erb
<h1>About us...</h1>

<p>
    <%= @about_me%>
</p>

app/views/home/contact.html.erb
Contact me

app/views/home/index.html.erb
<h1>Hello World</h1>
<p>This is my first Rails Webpage...</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Friends app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render "home/header" %>

    <div class="container">
    <br/>
    <% if notice %>
      <%= render "layouts/alerts" %>  
    <% end %>
      <br/>
      
      <%= yield %>
    </div>

    
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>